name: mind_easy
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  bloc: ^8.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  flutter_svg: ^2.0.11
  json_annotation: ^4.9.0
  equatable: ^2.0.5
  flutter_riverpod: ^3.0.0-dev.3
  riverpod_annotation: ^3.0.0-dev.3

dev_dependencies:
  riverpod_generator: ^3.0.0-dev.11
  riverpod_lint: ^3.0.0-dev.4
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0


dependency_overrides:
  meta: ^1.15.0

flutter_gen:
  assets:
    outputs:
      class_name: MindAssets
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)
  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: false
    rive: false
    lottie: false

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/svg/
    - assets/icons/
    - assets/images/
    - assets/dummy_models/
  fonts:
    - family: New York Extra Large
      fonts:
        - asset: assets/fonts/NewYorkExtraLargeRegular.otf
          weight: 400
        - asset: assets/fonts/NewYorkExtraLargeMedium.otf
          weight: 500
        - asset: assets/fonts/NewYorkExtraLargeBold.otf
          weight: 700
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
